#!/bin/bash
echo -e "Please provide filename you want to create: \c"
read -r file
touch /home/sudeep/scripts/$file.sh
echo '#!/bin/bash' > /home/sudeep/scripts/$file.sh 
echo '#Purpose: ' >>  /home/sudeep/scripts/$file.sh
echo '#Version: ' >>  /home/sudeep/scripts/$file.sh
echo '#Created Date:' `date` >>  /home/sudeep/scripts/$file.sh
echo '#Modified Date:' >>  /home/sudeep/scripts/$file.sh
echo '#Author: Sudeep Sharma' >>  /home/sudeep/scripts/$file.sh
echo '# START #' >>  /home/sudeep/scripts/$file.sh
echo '# END #' >>  /home/sudeep/scripts/$file.sh

`chmod 777 $file.sh`
